### ISSUE TITLE
Extracting keywords to be used elsewhere?

### ISSUE THREAD

**Issue by mofman** [venveo/craft-documentsearch#13]
We're using Algolia along with https://github.com/studioespresso/craft-scout to index our site. Wondering if there is an ability to extract the keywords for indexing elsewhere? 

Thanks

**Comment by Mosnar** [comment]
@mofman You should be able to access the extracted keywords by accessing the property `contentKeywords` off of an asset. For example:

```twig
{% set keywords = craft.assets.kind('pdf').one().contentKeywords %}
```

Keep in mind, this will trigger the document to be downloaded and rescanned. If you wanted to keep the existing saved keywords, you'd need to query the search index table manually, which might not be the best idea.

**Comment by mofman** [comment]
@Mosnar thanks for the response, yes both these idea seem ideal, I'll have to experiment to see which is appropriate for our use case.
