### ISSUE TITLE
Still working? No documents indexing and no record of contentkeyword in index

### ISSUE THREAD

**Issue by rickmills** [venveo/craft-documentsearch#7]
I was wondering if you could confirm if this plugin still works with the latest Craft 3 release. I've set it up and attached a few very basic text only pdf files to content and even after running `craft document-search/parse-documents/index-all` don't seem to be getting anything indexes.

Looking at a previous issue #1 there was a mention of a `contentkeywords` field containing the extracted search terms. Looking through my searchindex db table that field is never mentioned, so I'm wondering if I've just missed something here - was I supposed to add a `contentkeywords` field to the assets so it can store this, or should the plugin be handling it?

Many thanks

**Comment by Mosnar** [comment]
For posterity - everything still works. I've used it just fine with Craft 3.6. There are no fields added automatically, the contentkeywords field is just stored in the search index as if it was a field.

Not sure why you had issues, but my guess would be that something was misconfigured or there's some edge case I haven't run into.
