### ISSUE TITLE
Rename to PDF Document Search

### ISSUE THREAD

**Issue by jlopezmt** [venveo/craft-documentsearch#8]
Since that seems to be the primary use case.

**Comment by Mosnar** [comment]
Are there other document types you're interested in indexing?

**Comment by jlopezmt** [comment]
I thought this would only pull pdfs. If it is capable of doing more that
would be great, and also great to list.

At Your Service,

[image: employeeHeadshot][image: MilesLogo]

*Joed Lopez*Software Coordinator
(800) 496-8001
milestechnologies.com
<https://www.milestechnologies.com/>
[image: Facebook icon] <https://www.facebook.com/MilesTechnologies> [image:
LinkedIn icon] <https://www.linkedin.com/company/miles-technologies/> [image:
YouTube icon] <https://www.youtube.com/channel/UCnaCrcKd_ewigK4y3teXQ9g>
